update all required files to up project, fix up from clone

diff --git a/docker/app/Dockerfile.dev b/docker/app/Dockerfile.dev
--- a/docker/app/Dockerfile.dev
+++ b/docker/app/Dockerfile.dev
@@ -1,12 +1,18 @@
 FROM spiralscout/roadrunner:2024.1 AS roadrunner
 FROM $PARENT_IMAGE
 
+ARG USER=backend
+ARG GROUP=backend
+ARG UID=1000
+ARG GID=1000
+
 ENV \
     PS1='\[\033[1;32m\]\[\033[1;36m\][\u@\h] \[\033[1;34m\]\w\[\033[0;35m\] \[\033[1;36m\]# \[\033[0m\]' \
     COMPOSER_HOME="/tmp/composer" \
     OWN_SSL_CERT_DIR="/ssl-cert" \
     OWN_SSL_CERT_LIFETIME=1095 \
-    XDEBUG_VERSION="3.3.2"
+    XDEBUG_VERSION="3.3.2" \
+    GOSU_VERSION="1.17"
 
 # persistent / runtime deps
 ENV PHPIZE_DEPS \
@@ -17,8 +23,6 @@ ENV PHPIZE_DEPS \
     make \
     g++ \
     gcc
-
-COPY --from=roadrunner /usr/bin/rr /usr/bin/rr
 
 RUN set -xe \
     && apk add --no-cache --virtual .build-deps ${PHPIZE_DEPS} \
@@ -43,26 +47,60 @@ RUN set -xe \
         && openssl x509 -req -days ${OWN_SSL_CERT_LIFETIME} -in cert.csr -signkey self-signed.key -out self-signed.crt \
         && ls -lh
 
+RUN mkdir -p /app && adduser --uid "$UID" -D -h /app -s /bin/bash -g "$GROUP" "$USER" && echo "$USER:som3lo0gpassw@rdz" | chpasswd
+
+RUN set -eux; \
+	apk add --no-cache --virtual .gosu-deps \
+		ca-certificates \
+		dpkg \
+		gnupg \
+	; \
+	\
+	dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
+	wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
+	wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
+	\
+# verify the signature
+	export GNUPGHOME="$(mktemp -d)"; \
+	gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
+	gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
+	command -v gpgconf && gpgconf --kill all || :; \
+	rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
+	\
+# clean up fetch dependencies
+	apk del --no-network .gosu-deps; \
+	\
+	chmod +x /usr/local/bin/gosu; \
+# verify that the binary works
+	gosu --version; \
+	gosu nobody true
+
+RUN ls -la
+
+COPY ./bin/ /app/bin/
+COPY ./config/ /app/config/
+COPY ./public/ /app/public/
+COPY ./tests/ /app/tests/
+COPY ./src/ /app/src/
+COPY ./.rr.dev.yaml /app/.rr.dev.yaml
+COPY ./symfony.lock /app/symfony.lock
 COPY ./composer.* /app/
+COPY ./.env /app/.env
+
 COPY ./docker/shared/keep-alive.sh /usr/local/bin/keep-alive.sh
+COPY ./docker/app/entry/entrypoint-dev.sh /usr/local/bin/entrypoint
+RUN chmod +x /usr/local/bin/entrypoint
+
+COPY --from=roadrunner /usr/bin/rr /usr/bin/rr
 
 WORKDIR /app
 
-#RUN set -xe \
-#    && composer install -vvv \
-#        --no-interaction \
-#        --no-autoloader \
-#        --prefer-dist  \
-#        --no-suggest \
-#        --no-ansi \
-#        --no-scripts \
-#    && composer dump-autoload \
-#    && rr -h
-
 EXPOSE 80
 EXPOSE 443
-
 VOLUME ["/app"]
 
-#CMD ["rr", "serve", "-c", "/app/.rr.yml"]
-CMD ["/usr/local/bin/keep-alive.sh"]
+# repass root for using gosu in the future
+USER root
+
+ENTRYPOINT ["/usr/local/bin/entrypoint"]
+CMD ["rr", "serve", "--debug", "-c", "/app/.rr.dev.yaml"]
