update all required files to up project, fix up from clone

diff --git a/docker/app/Dockerfile.prod b/docker/app/Dockerfile.prod
--- a/docker/app/Dockerfile.prod
+++ b/docker/app/Dockerfile.prod
@@ -1,13 +1,60 @@
 FROM spiralscout/roadrunner:2024.1 AS roadrunner
 FROM $PARENT_IMAGE
 
+ARG USER=backend
+ARG GROUP=backend
+ARG UID=1000
+ARG GID=1000
+
 ENV \
     PS1='\[\033[1;32m\]\[\033[1;36m\][\u@\h] \[\033[1;34m\]\w\[\033[0;35m\] \[\033[1;36m\]# \[\033[0m\]' \
-    COMPOSER_HOME="/tmp/composer"
+    COMPOSER_HOME="/tmp/composer" \
+    GOSU_VERSION="1.17"
+
+RUN mkdir -p /app && adduser --uid "$UID" -D -h /app -s /bin/bash -g "$GROUP" "$USER" && echo "$USER:som3lo0gpassw@rdz" | chpasswd
+RUN set -eux; \
+	apk add --no-cache --virtual .gosu-deps \
+		ca-certificates \
+		dpkg \
+		gnupg \
+	; \
+	\
+	dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
+	wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
+	wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
+	\
+# verify the signature
+	export GNUPGHOME="$(mktemp -d)"; \
+	gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
+	gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
+	command -v gpgconf && gpgconf --kill all || :; \
+	rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
+	\
+# clean up fetch dependencies
+	apk del --no-network .gosu-deps; \
+	\
+	chmod +x /usr/local/bin/gosu; \
+# verify that the binary works
+	gosu --version; \
+	gosu nobody true
+
+RUN ls -la
+
+COPY ./bin/ /app/bin/
+COPY ./config/ /app/config/
+COPY ./public/ /app/public/
+COPY ./tests/ /app/tests/
+COPY ./src/ /app/src/
+COPY ./.rr.dev.yaml /app/.rr.dev.yaml
+COPY ./symfony.lock /app/symfony.lock
+COPY ./composer.* /app/
+COPY ./.env /app/.env
+
+COPY ./docker/shared/keep-alive.sh /usr/local/bin/keep-alive.sh
+COPY ./docker/app/entry/entrypoint-dev.sh /usr/local/bin/entrypoint
+RUN chmod +x /usr/local/bin/entrypoint
 
 COPY --from=roadrunner /usr/bin/rr /usr/bin/rr
-
-COPY ./composer.* /app/
 
 WORKDIR /app
 
@@ -28,4 +75,8 @@ EXPOSE 443
 
 VOLUME ["/app"]
 
-CMD ["rr", "serve", "-c", "/app/.rr.yml"]
+# repass root for using gosu in the future
+USER root
+
+ENTRYPOINT ["/usr/local/bin/entrypoint"]
+CMD ["rr", "serve", "-c", "/app/.rr.yaml"]
